// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

/*
Package backend is a generated protocol buffer package.

It is generated from these files:
	backend.proto

It has these top-level messages:
	RegisterUserRequest
	RegisterUserResponse
*/
package backend

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterUserRequest struct {
	Username     string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	PasswordHash string `protobuf:"bytes,2,opt,name=passwordHash" json:"passwordHash,omitempty"`
	DeviceId     string `protobuf:"bytes,3,opt,name=deviceId" json:"deviceId,omitempty"`
}

func (m *RegisterUserRequest) Reset()                    { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()               {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterUserRequest) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *RegisterUserRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type RegisterUserResponse struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *RegisterUserResponse) Reset()                    { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()               {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*RegisterUserRequest)(nil), "backend.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "backend.RegisterUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Spawn service

type SpawnClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
}

type spawnClient struct {
	cc *grpc.ClientConn
}

func NewSpawnClient(cc *grpc.ClientConn) SpawnClient {
	return &spawnClient{cc}
}

func (c *spawnClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := grpc.Invoke(ctx, "/backend.Spawn/RegisterUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Spawn service

type SpawnServer interface {
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
}

func RegisterSpawnServer(s *grpc.Server, srv SpawnServer) {
	s.RegisterService(&_Spawn_serviceDesc, srv)
}

func _Spawn_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpawnServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Spawn/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpawnServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Spawn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backend.Spawn",
	HandlerType: (*SpawnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _Spawn_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4a, 0x4c, 0xce,
	0x4e, 0xcd, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x0a, 0xb9,
	0x84, 0x83, 0x52, 0xd3, 0x33, 0x8b, 0x4b, 0x52, 0x8b, 0x42, 0x8b, 0x53, 0x8b, 0x82, 0x52, 0x0b,
	0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x4a, 0x8b, 0x53, 0x8b, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x25, 0x2e, 0x9e, 0x82, 0xc4, 0xe2,
	0xe2, 0xf2, 0xfc, 0xa2, 0x14, 0x8f, 0xc4, 0xe2, 0x0c, 0x09, 0x26, 0xb0, 0x3c, 0x8a, 0x18, 0x48,
	0x7f, 0x4a, 0x6a, 0x59, 0x66, 0x72, 0xaa, 0x67, 0x8a, 0x04, 0x33, 0x44, 0x3f, 0x8c, 0xaf, 0xe4,
	0xc0, 0x25, 0x82, 0x6a, 0x65, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x10, 0x1f, 0x17, 0x53, 0x66,
	0x0a, 0xd4, 0x36, 0xa6, 0xcc, 0x14, 0x21, 0x09, 0x2e, 0xf6, 0xe2, 0xd2, 0xe4, 0xe4, 0xd4, 0xe2,
	0x62, 0xb0, 0x15, 0x1c, 0x41, 0x30, 0xae, 0x51, 0x18, 0x17, 0x6b, 0x70, 0x41, 0x62, 0x79, 0x9e,
	0x90, 0x2f, 0x17, 0x0f, 0xb2, 0x51, 0x42, 0x32, 0x7a, 0x30, 0x6f, 0x62, 0xf1, 0x94, 0x94, 0x2c,
	0x0e, 0x59, 0x88, 0xfd, 0x4a, 0x0c, 0x49, 0x6c, 0xe0, 0xc0, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xf6, 0x90, 0x39, 0x51, 0x2d, 0x01, 0x00, 0x00,
}
