// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

/*
Package backend is a generated protocol buffer package.

It is generated from these files:
	backend.proto

It has these top-level messages:
	Empty
	Device
	CreateUserRequest
	CreateUserResponse
	AddDeviceRequest
	LoginRequest
	ConfirmRequest
*/
package backend

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Device struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Locale string `protobuf:"bytes,3,opt,name=locale" json:"locale,omitempty"`
	Lang   string `protobuf:"bytes,4,opt,name=lang" json:"lang,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Device) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *Device) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type CreateUserRequest struct {
	Username     string  `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	PasswordHash string  `protobuf:"bytes,2,opt,name=passwordHash" json:"passwordHash,omitempty"`
	Device       *Device `protobuf:"bytes,3,opt,name=device" json:"device,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *CreateUserRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type CreateUserResponse struct {
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AddDeviceRequest struct {
	UserId string  `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	Device *Device `protobuf:"bytes,2,opt,name=device" json:"device,omitempty"`
}

func (m *AddDeviceRequest) Reset()                    { *m = AddDeviceRequest{} }
func (m *AddDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*AddDeviceRequest) ProtoMessage()               {}
func (*AddDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddDeviceRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddDeviceRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type LoginRequest struct {
	SessionId   string                     `protobuf:"bytes,1,opt,name=sessionId" json:"sessionId,omitempty"`
	UserId      string                     `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	Device      *Device                    `protobuf:"bytes,3,opt,name=device" json:"device,omitempty"`
	LoginTime   *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=loginTime" json:"loginTime,omitempty"`
	LoginIP     string                     `protobuf:"bytes,5,opt,name=loginIP" json:"loginIP,omitempty"`
	LoginRegion string                     `protobuf:"bytes,6,opt,name=loginRegion" json:"loginRegion,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *LoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *LoginRequest) GetLoginTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.LoginTime
	}
	return nil
}

func (m *LoginRequest) GetLoginIP() string {
	if m != nil {
		return m.LoginIP
	}
	return ""
}

func (m *LoginRequest) GetLoginRegion() string {
	if m != nil {
		return m.LoginRegion
	}
	return ""
}

type ConfirmRequest struct {
	Kind      string `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=sessionId" json:"sessionId,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=userId" json:"userId,omitempty"`
	DeviceId  string `protobuf:"bytes,4,opt,name=deviceId" json:"deviceId,omitempty"`
	Code      string `protobuf:"bytes,5,opt,name=code" json:"code,omitempty"`
}

func (m *ConfirmRequest) Reset()                    { *m = ConfirmRequest{} }
func (m *ConfirmRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfirmRequest) ProtoMessage()               {}
func (*ConfirmRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ConfirmRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ConfirmRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ConfirmRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ConfirmRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *ConfirmRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "backend.Empty")
	proto.RegisterType((*Device)(nil), "backend.Device")
	proto.RegisterType((*CreateUserRequest)(nil), "backend.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "backend.CreateUserResponse")
	proto.RegisterType((*AddDeviceRequest)(nil), "backend.AddDeviceRequest")
	proto.RegisterType((*LoginRequest)(nil), "backend.LoginRequest")
	proto.RegisterType((*ConfirmRequest)(nil), "backend.ConfirmRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Spawn service

type SpawnClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	AddDevice(ctx context.Context, in *AddDeviceRequest, opts ...grpc.CallOption) (*Empty, error)
	HandleLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Empty, error)
	DoConfirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*Empty, error)
}

type spawnClient struct {
	cc *grpc.ClientConn
}

func NewSpawnClient(cc *grpc.ClientConn) SpawnClient {
	return &spawnClient{cc}
}

func (c *spawnClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/backend.Spawn/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spawnClient) AddDevice(ctx context.Context, in *AddDeviceRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/backend.Spawn/AddDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spawnClient) HandleLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/backend.Spawn/HandleLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spawnClient) DoConfirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/backend.Spawn/DoConfirm", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Spawn service

type SpawnServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	AddDevice(context.Context, *AddDeviceRequest) (*Empty, error)
	HandleLogin(context.Context, *LoginRequest) (*Empty, error)
	DoConfirm(context.Context, *ConfirmRequest) (*Empty, error)
}

func RegisterSpawnServer(s *grpc.Server, srv SpawnServer) {
	s.RegisterService(&_Spawn_serviceDesc, srv)
}

func _Spawn_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpawnServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Spawn/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpawnServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spawn_AddDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpawnServer).AddDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Spawn/AddDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpawnServer).AddDevice(ctx, req.(*AddDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spawn_HandleLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpawnServer).HandleLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Spawn/HandleLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpawnServer).HandleLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spawn_DoConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpawnServer).DoConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Spawn/DoConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpawnServer).DoConfirm(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Spawn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backend.Spawn",
	HandlerType: (*SpawnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Spawn_CreateUser_Handler,
		},
		{
			MethodName: "AddDevice",
			Handler:    _Spawn_AddDevice_Handler,
		},
		{
			MethodName: "HandleLogin",
			Handler:    _Spawn_HandleLogin_Handler,
		},
		{
			MethodName: "DoConfirm",
			Handler:    _Spawn_DoConfirm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xdd, 0xc4, 0x69, 0x26, 0x25, 0xc0, 0x48, 0x80, 0x31, 0x48, 0x54, 0xbe, 0xc0, 0x01,
	0xb9, 0x52, 0x90, 0x10, 0x57, 0xd4, 0x22, 0x1a, 0x89, 0x03, 0x4a, 0x8b, 0xc4, 0x75, 0x93, 0x9d,
	0x9a, 0x55, 0xed, 0x5d, 0xe3, 0x75, 0xa8, 0x90, 0xf8, 0x05, 0xfc, 0x4d, 0xfe, 0x05, 0x27, 0xe4,
	0xdd, 0xf5, 0xc6, 0xa1, 0x4d, 0x6f, 0xf3, 0xe5, 0x79, 0xef, 0xcd, 0x3e, 0xc3, 0xbd, 0x25, 0x5b,
	0x5d, 0x91, 0xe4, 0x59, 0x55, 0xab, 0x46, 0xe1, 0xc8, 0xa5, 0xc9, 0x8b, 0x5c, 0xa9, 0xbc, 0xa0,
	0x63, 0x53, 0x5e, 0xae, 0x2f, 0x8f, 0x1b, 0x51, 0x92, 0x6e, 0x58, 0x59, 0xd9, 0xc9, 0x74, 0x04,
	0xc3, 0x0f, 0x65, 0xd5, 0xfc, 0x4c, 0xbf, 0x42, 0x74, 0x4a, 0x3f, 0xc4, 0x8a, 0x70, 0x0a, 0xa1,
	0xe0, 0x71, 0x70, 0x14, 0xbc, 0x1a, 0x2f, 0x42, 0xc1, 0x11, 0x61, 0x20, 0x59, 0x49, 0x71, 0x68,
	0x2a, 0x26, 0xc6, 0xc7, 0x10, 0x15, 0x6a, 0xc5, 0x0a, 0x8a, 0xf7, 0x4d, 0xd5, 0x65, 0xed, 0x6c,
	0xc1, 0x64, 0x1e, 0x0f, 0xec, 0x6c, 0x1b, 0xa7, 0xbf, 0xe0, 0xe1, 0x49, 0x4d, 0xac, 0xa1, 0x2f,
	0x9a, 0xea, 0x05, 0x7d, 0x5f, 0x93, 0x6e, 0x30, 0x81, 0x83, 0xb5, 0xa6, 0xda, 0x2c, 0xb6, 0x50,
	0x3e, 0xc7, 0x14, 0x0e, 0x2b, 0xa6, 0xf5, 0xb5, 0xaa, 0xf9, 0x19, 0xd3, 0xdf, 0x1c, 0xf0, 0x56,
	0x0d, 0x5f, 0x42, 0xc4, 0x0d, 0x5d, 0x43, 0x60, 0x32, 0xbb, 0x9f, 0x75, 0x17, 0xb0, 0x2a, 0x16,
	0xae, 0x9d, 0xbe, 0x06, 0xec, 0xa3, 0xeb, 0x4a, 0x49, 0x6d, 0xf8, 0xb7, 0x70, 0xf3, 0x4e, 0xa7,
	0xcb, 0xd2, 0x73, 0x78, 0xf0, 0x9e, 0x73, 0xb7, 0xc2, 0x51, 0xdd, 0x31, 0xdb, 0xa3, 0x10, 0xde,
	0x4d, 0xe1, 0x4f, 0x00, 0x87, 0x9f, 0x54, 0x2e, 0x64, 0xb7, 0xf1, 0x39, 0x8c, 0x35, 0x69, 0x2d,
	0x94, 0xf4, 0x4b, 0x37, 0x85, 0x1e, 0x5e, 0xb8, 0x03, 0xef, 0x6e, 0xc9, 0xf8, 0x0e, 0xc6, 0x45,
	0x0b, 0x77, 0x21, 0x4a, 0x32, 0x2f, 0x31, 0x99, 0x25, 0x99, 0x35, 0x42, 0xd6, 0x19, 0x21, 0xbb,
	0xe8, 0x8c, 0xb0, 0xd8, 0x0c, 0x63, 0x0c, 0x23, 0x93, 0xcc, 0x3f, 0xc7, 0x43, 0x83, 0xdd, 0xa5,
	0x78, 0x04, 0x93, 0xc2, 0x4a, 0xc8, 0x85, 0x92, 0x71, 0x64, 0xba, 0xfd, 0x52, 0xfa, 0x3b, 0x80,
	0xe9, 0x89, 0x92, 0x97, 0xa2, 0x2e, 0x3b, 0x9d, 0x08, 0x83, 0x2b, 0x21, 0x3b, 0x89, 0x26, 0xde,
	0xd6, 0x1e, 0xee, 0xd6, 0xbe, 0xbf, 0xa5, 0x3d, 0x81, 0x03, 0x2b, 0x6e, 0xce, 0x9d, 0xb7, 0x7c,
	0xde, 0xa2, 0xac, 0x14, 0x27, 0xc7, 0xd8, 0xc4, 0xb3, 0xbf, 0x01, 0x0c, 0xcf, 0x2b, 0x76, 0x2d,
	0xf1, 0x23, 0xc0, 0xe6, 0xfd, 0x31, 0xf1, 0x37, 0xbb, 0x61, 0xc9, 0xe4, 0xd9, 0xad, 0x3d, 0x6b,
	0x98, 0x74, 0xaf, 0xbd, 0xaa, 0xb7, 0x06, 0x3e, 0xf5, 0xb3, 0xff, 0xdb, 0x25, 0x99, 0xfa, 0x96,
	0xfd, 0xb1, 0xf6, 0xf0, 0x2d, 0x4c, 0xce, 0x98, 0xe4, 0x05, 0x19, 0x13, 0xe0, 0x23, 0x3f, 0xd0,
	0x37, 0xc5, 0xad, 0xdf, 0x8d, 0x4f, 0x95, 0x3b, 0x29, 0x3e, 0xd9, 0xb0, 0xdb, 0x3a, 0xf2, 0xcd,
	0xef, 0x96, 0x91, 0x79, 0xe4, 0x37, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x71, 0xab, 0x38, 0x16,
	0x15, 0x04, 0x00, 0x00,
}
